### ISSUE TITLE
HiQnet to Node Red

### ISSUE THREAD

**Issue by DerTechnikerHD** [dudest/node-red-contrib-soundweb#10]
Hey,

I have an AKG Hub4000 with HiQnet functions. Now I want to use Node-RED to visualize the value of my battery. Can you help me with this little task?"

Feel free to ask if you need further assistance! 😊

**Comment by dudest** [comment]
@DerTechnikerHD,

I just checked to see if this is possible, it looks like it can be achieved. You will need to set your project up in audio architect with a *third party control* object to obtain the address for the control you want to hook on to. In node-red **soundweb-Control** set the command type to `set state variable` and the scale type to  `discrete` . If you supply a valid HiQnet address the node should automatically subscribe. Check the links in the readme for the HiQnet spec and pay close attention to byte substitution when entering the address.

I won't program it for you as this is not a service I provide for free. Best of luck with your project 👍
