### ISSUE TITLE
Change soundweb-Control Address parameter dynamically

### ISSUE THREAD

**Issue by Daniel-Higgott** [dudest/node-red-contrib-soundweb#5]
I would like to be able to change the Address parameter of the soundweb-Control node programatically. The use case for this would be to have a single instance of the node which could be reused to set values at multiple HiQNet addresses.

I can't see this in the documentation, but please do let me know if it is possible. Assuming this is not possible, it would be a great addition.

Many thanks for your work on this Node.

Dan

**Comment by dudest** [comment]
Hello @Daniel-Higgott,

Glad to hear the node is getting some use out in the wild!

You are correct that this can't be done in the current release; however, it is a reasonable feature request that I may implement down the road. I can't offer a timeline as I no longer have a BSS device to bench test with.

Best,
Alex

**Comment by Daniel-Higgott** [comment]
Hi Alex,

No problem! Yes, I’m really pleased to see this Node. My current project has a large Soundweb deployment and it has simplified the Node Red programming significantly. Thank you.

All the best,

Dan

**Comment by dudest** [comment]
Hello @Daniel-Higgott,

I created a v1.0.6 branch and did some light testing. It should work. If you would be so kind as to clone and test it on a Soundweb device I'll be able to merge and publish officially. Let me know.

Best,
Alex

**Comment by Daniel-Higgott** [comment]
Thanks so much!

We are in the middle of a project at the moment, which could make testing this a little tricky, but lets see what we can do. Bringing this to  @AndyFug 's attention.
